### ISSUE TITLE
Question on Enterprise-scale Landing Zones

### ISSUE THREAD

**Issue by nnellans** [adstuart/azure-privatelink-multiregion#2]
Hi Adam, thanks for putting this together.  This has been very helpful.

You mention the following about Enterprise Scale Landing Zone architectures:

> The team within Microsoft responsible for Enterprise Scale Landing Zones documentation are currently working on updating the automation associated with this topic to provide flexibility in its deployment, to cater for both architecture options presented in this article.

Are you aware of any updates regarding this?  I'm struggling to find anything about it.

**Comment by jtracey93** [comment]
Hey @nnellans,

We are still looking at this in the ALZ (ESLZ) team, and are working with product teams to try and get to a agreed upon architecture and approach. Unfortunately, its moving slower than everyone would like, but its a complex topic so understandable.

**Comment by nnellans** [comment]
@jtracey93 Thanks for the reply!  Glad to know its still being worked on!
